### ISSUE TITLE
Unexpected error in the result of MF conversion

### ISSUE THREAD

**Issue by fedorov** [afshinmessiah/PyDicomVerify#6]
The following error is not present in the source images, but is there for the MF conversion result. It would be good to document why this is the case:

```
Error - Missing attribute Type 1C Conditional Element=<ReferencedImageEvidenceSequence> 
  Module=<MRImageAndSpectroscopyInstanceMacro>
```

**Comment by fedorov** [comment]
Looks like this is because the required ReferencedImageEvidenceSequence, which should list all instances in our case referenced from per-frame FGs, see https://dicom.innolitics.com/ciods/legacy-converted-enhanced-mr-image/enhanced-mr-image/00089092.

Sample dataset: https://www.dropbox.com/s/tshrmkurka3eqzf/4.000000-t2tsetra-00702.zip?dl=0

**Comment by fedorov** [comment]
@dclunie is my interpretation of the standard correct that if we reference instances from FG sequences in the legacy converted enhanced object, those instances should also be referenced from ReferencedImageEvidenceSequence?

**Comment by fedorov** [comment]
@dclunie related to this question, if we have a situation where a source non-enhanced instance references some other instances via `ReferencedImageSequence`, and then `ReferencedImageSequence` is propagated into per-frame FG `ReferencedImageSequence`, should those indirectly referenced instances be referenced from `ReferencedImageEvidenceSequence`?

We note that `com.pixelmed.dicom.MultiFrameImageFactory` does not populate `ReferencedImageEvidenceSequence` either, while `dciodvfy` does complain that missing `ReferencedImageEvidenceSequence` is an error.

Attached is the result of conversion using `com.pixelmed.dicom.MultiFrameImageFactory`, and the source series is referenced above via dropbox link.
[1.3.6.1.4.1.5962.99.1.3549.8838.1619557662817.1.1.0.4.1.zip](https://github.com/ImagingDataCommons/PyDicomVerify/files/6387678/1.3.6.1.4.1.5962.99.1.3549.8838.1619557662817.1.1.0.4.1.zip)

**Comment by dclunie** [comment]
The short answer is yes, the ReferencedImageEvidenceSequence is required to be present in this situation, per:

http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.13.2.html#para_9f2e3e63-72ff-4ec7-9931-ed0250c8546b

so the error reported by dciodvfy is correct.

This was a reasonable condition for the true enhanced family of objects, and a side effect that I didn't think of when I included the Enhanced MR Image Module and hence the MR Image and Spectroscopy Instance Macro Attributes in the legacy MR IOD. However, it is what it is (unless we put in a CP to relax this constraint).

Note that this also applies to Source Image Evidence Sequence. and to converted CT and PET images.

This means that given a reference to a SOP Instance, one needs to dig out the Study/Series UIDs for that referenced image and populate ReferencedImageEvidenceSequence accordingly.

Currently, com.pixelmed.dicom.MultiFrameImageFactory does not try to do that (and given the scope of its input, would only be able to do that if the referenced instances were part of the set it was trying to convert).

This also raises the question of what should be referenced in the first place - i.e., if a converted frame references another frame that is being converted, then the reference should be changed to the new UID and frame number, not left referencing the unconverted image; also, if not all frames in a study are being converted (e.g., perhaps not localizers), then those references should be left alone. This subject probably deserves a separate tracker item.

**Comment by fedorov** [comment]
Per discussion with David, for now decided not to populate ReferencedImageEvidenceSequence since 1) only items from ReferencedImageSequence should be included there, and we do not have sufficient information to populate study/series items; 2) references from ConversionSourceAttributesSequence should not be included in ReferencedImageEvidenceSequence. David will work on a CP to relax the requirement for including references while creating legacy converted objects.

**Comment by dclunie** [comment]
[cp_dac586_referencedimageevidencelegacyconverted.pdf](https://github.com/ImagingDataCommons/PyDicomVerify/files/6406057/cp_dac586_referencedimageevidencelegacyconverted.pdf)

**Comment by fedorov** [comment]
Thank you David. Closing this issue, since in this aspect of the conversion the behavior of the converter is consistent with the standard.
